# Generated by Django 5.2.17 on 2026-08-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Élève / Étudiant'), ('TEACHER', 'Enseignant / Mentor'), ('PARENT', 'Parent / Tuteur')], default='STUDENT', max_length=10),
        ),
    ]
