# Generated by Django 5.2.17 on 2026-09-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherapplication',
            name='review_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='reviewed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='mentor_application_reviews',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
