"""
Django settings for school_on project.

Generated by 'django-admin startproject' using Django 4.0.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from datetime import timedelta
import email
import os
from pathlib import Path

from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = os.getenv('DJANGO_DEBUG', 'true').lower() == 'true'
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be configured when DEBUG is disabled.')
    SECRET_KEY = 'development-only-insecure-key-change-before-deployment'

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = [host.strip() for host in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1]').split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # applications tierces
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'drf_spectacular',
    'corsheaders',
    'school_on',
    # mes applications personnalisées
    'utilisateurs',
    'bookings',
    'payments',
    'courses',
    'forum',
    'notifications',
    'certificates',
]

AUTH_USER_MODEL = 'utilisateurs.CustomUser'

SITE_ID = 1

REST_USE_JWT = True
JWT_AUTH_COOKIE = 'school_on_auth'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

CORS_ALLOW_ALL_ORIGINS = False
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    
    'allauth.account.middleware.AccountMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'school_on.urls'

ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*']


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'BLACKLIST_FLAVOR': 'rest_framework_simplejwt.token_blacklist.models.BlacklistedToken',
    'AUTH_HEADER_TYPES': ('Bearer',),
}

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': 'YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com',
            'secret': 'YOUR_GOOGLE_CLIENT_SECRET',
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ]
    }
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]
if os.getenv('CORS_ALLOWED_ORIGINS'):
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if origin.strip()]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
if os.getenv('CSRF_TRUSTED_ORIGINS'):
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()]
CORS_ALLOW_CREDENTIALS = True

PAYMENT_FAKE_ENABLED = DEBUG
PAYMENT_LUMICASH_ENABLED = os.getenv('PAYMENT_LUMICASH_ENABLED', 'true').lower() == 'true'
PAYMENT_LUMICASH_API_URL = os.getenv('PAYMENT_LUMICASH_API_URL', os.getenv('LUMICASH_API_URL', ''))
PAYMENT_LUMICASH_API_KEY = os.getenv('PAYMENT_LUMICASH_API_KEY', os.getenv('LUMICASH_CLIENT_ID', ''))
PAYMENT_LUMICASH_SECRET = os.getenv('PAYMENT_LUMICASH_SECRET', os.getenv('LUMICASH_CLIENT_SECRET', ''))
PAYMENT_LUMICASH_MERCHANT_ID = os.getenv('PAYMENT_LUMICASH_MERCHANT_ID', os.getenv('LUMICASH_MERCHANT_ID', ''))
PAYMENT_LUMICASH_CALLBACK_URL = os.getenv('PAYMENT_LUMICASH_CALLBACK_URL', os.getenv('LUMICASH_CALLBACK_URL', ''))
PAYMENT_BITLIBERA_ENABLED = os.getenv('PAYMENT_BITLIBERA_ENABLED', 'false').lower() == 'true'
PAYMENT_BITLIBERA_API_URL = os.getenv('PAYMENT_BITLIBERA_API_URL', 'https://exchanger.bitlibera.com')
PAYMENT_BITLIBERA_API_KEY = os.getenv('PAYMENT_BITLIBERA_API_KEY', '')
PAYMENT_BITLIBERA_SECRET = os.getenv('PAYMENT_BITLIBERA_SECRET', '')
PAYMENT_BITLIBERA_MERCHANT_ID = os.getenv('PAYMENT_BITLIBERA_MERCHANT_ID', '')
PAYMENT_BITLIBERA_CALLBACK_URL = os.getenv('PAYMENT_BITLIBERA_CALLBACK_URL', '')
PAYMENT_PLATFORM_FEE_RATE = os.getenv('PAYMENT_PLATFORM_FEE_RATE', '0.05')
PAYMENT_WEBHOOK_SECRET = os.getenv('PAYMENT_WEBHOOK_SECRET', 'dev-only-webhook-secret' if DEBUG else '')
PAYMENT_BLINK_ENABLED = os.getenv('PAYMENT_BLINK_ENABLED', 'false').lower() == 'true'
PAYMENT_BLINK_API_URL = os.getenv('PAYMENT_BLINK_API_URL', 'https://api.blink.sv/graphql')
PAYMENT_BLINK_WS_URL = os.getenv('PAYMENT_BLINK_WS_URL', 'wss://ws.blink.sv/graphql')
PAYMENT_BLINK_API_KEY = os.getenv('PAYMENT_BLINK_API_KEY', os.getenv('BLINK_API_KEY', ''))
PAYMENT_BLINK_WALLET_ID = os.getenv('PAYMENT_BLINK_WALLET_ID', os.getenv('BLINK_WALLET_ID', ''))
PAYMENT_BLINK_BIF_SATS = os.getenv('PAYMENT_BLINK_BIF_SATS', '0')
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@schoolon.com')
CERTIFICATE_PUBLIC_BASE_URL = os.getenv('CERTIFICATE_PUBLIC_BASE_URL', 'http://localhost:5173')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_on.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL', '')
DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600) if DATABASE_URL else {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

SPECTACULAR_SETTINGS = {
    'TITLE': 'School On API',
    'DESCRIPTION': 'API pour l\'application School On',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': True,
    'COMPONENT_SPLIT_REQUEST': True,
}


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
