# Generated by Django 6.0.7 on 2026-09-24 10:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_quizattempt_selected_question_ids'),
        ('forum', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='forumpost',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.forumpost'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_MODERATION', 'En attente de modération'), ('PUBLISHED', 'Publié'), ('HIDDEN', 'Masqué'), ('LOCKED', 'Verrouillé'), ('ARCHIVED', 'Archivé'), ('REMOVED', 'Retiré')], default='PUBLISHED', max_length=25),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='accepted_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_threads', to='forum.forumpost'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='content_type',
            field=models.CharField(choices=[('QUESTION', 'Question'), ('DISCUSSION', 'Discussion éducative'), ('EXERCISE_HELP', 'Aide sur un exercice'), ('RESOURCE', 'Ressource'), ('ORIENTATION', 'Orientation')], default='QUESTION', max_length=20),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_threads', to='courses.course'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='last_activity_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_threads', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_threads', to='courses.quiz'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='quiz_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_threads', to='courses.question'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='replies_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_MODERATION', 'En attente de modération'), ('PUBLISHED', 'Publié'), ('HIDDEN', 'Masqué'), ('LOCKED', 'Verrouillé'), ('ARCHIVED', 'Archivé'), ('REMOVED', 'Retiré')], default='PENDING_MODERATION', max_length=25),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='forum.communitycategory'),
        ),
        migrations.CreateModel(
            name='CommunityModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('APPROVE', 'Approuver'), ('HIDE', 'Masquer'), ('REMOVE', 'Retirer'), ('RESTORE', 'Restaurer'), ('LOCK_THREAD', 'Verrouiller')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='forum.forumpost')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='forum.forumthread')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('OFF_TOPIC', 'Hors sujet'), ('HARASSMENT', 'Harcèlement'), ('HATE_OR_ABUSE', 'Haine ou abus'), ('VIOLENCE', 'Violence ou menace'), ('SEXUAL_CONTENT', 'Contenu sexuel'), ('ILLEGAL_ACTIVITY', 'Activité illégale'), ('SPAM', 'Spam'), ('PERSONAL_DATA', 'Données personnelles'), ('MISINFORMATION', 'Désinformation'), ('OTHER', 'Autre')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('UNDER_REVIEW', 'En cours'), ('RESOLVED', 'Résolu'), ('DISMISSED', 'Classé')], default='OPEN', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_action', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum.forumpost')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_community_reports', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum.forumthread')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
