# Generated by Django 5.2.5 on 2026-09-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_study_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='student_signature_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
