# Generated by Django 6.0.7 on 2026-09-24 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorprofile',
            options={'ordering': ['-is_verified', 'id'], 'verbose_name': 'Profil mentor', 'verbose_name_plural': 'Profils mentors'},
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='education',
            field=models.TextField(blank=True, help_text='Diplômes et formations'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='experience',
            field=models.CharField(blank=True, help_text="Tranche d'expérience déclarée", max_length=100),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='headline',
            field=models.CharField(blank=True, help_text='Slogan du profil mentor', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='id_document',
            field=models.CharField(blank=True, help_text="Référence CNI / passeport ou URL du document d'identité", max_length=500),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='mentor_status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_VERIFICATION', 'Vérification en attente'), ('UNDER_REVIEW', 'En cours de révision'), ('NEEDS_INFORMATION', 'Informations requises'), ('VERIFIED', 'Vérifié'), ('REJECTED', 'Rejeté'), ('SUSPENDED', 'Suspendu')], default='DRAFT', help_text='Statut du parcours de vérification mentor (spec User & Mentor Journey).', max_length=30),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='public_location',
            field=models.CharField(blank=True, help_text='Localisation publique volontairement imprécise (« Gitega, Burundi »).', max_length=150),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='session_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='title',
            field=models.CharField(blank=True, help_text='Titre professionnel affiché', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='Burundi', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('education_level', models.CharField(blank=True, help_text='Niveau scolaire, ex. 9ème année, Terminale, Licence 1…', max_length=100)),
                ('school_name', models.CharField(blank=True, max_length=150)),
                ('interests', models.JSONField(blank=True, default=list, help_text="Domaines d'intérêt choisis par l'apprenant (liste de chaînes).")),
                ('learning_goal', models.TextField(blank=True)),
                ('profile_completion', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil apprenant',
                'verbose_name_plural': 'Profils apprenants',
            },
        ),
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_VERIFICATION', 'Vérification en attente'), ('UNDER_REVIEW', 'En cours de révision'), ('NEEDS_INFORMATION', 'Informations requises'), ('VERIFIED', 'Vérifié'), ('REJECTED', 'Rejeté'), ('SUSPENDED', 'Suspendu')], default='DRAFT', max_length=30)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='Burundi', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('motivation', models.TextField(blank=True)),
                ('professional_bio', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, help_text="Motif du refus ou demande d'information")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mentor_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidature mentor',
                'verbose_name_plural': 'Candidatures mentor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=150)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Non commencé'), ('IN_PROGRESS', 'En cours'), ('PASSED', 'Réussi'), ('FAILED', 'Échoué')], default='NOT_STARTED', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='utilisateurs.mentorapplication')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Évaluation de compétence',
                'verbose_name_plural': 'Évaluations de compétence',
            },
        ),
        migrations.CreateModel(
            name='MentorInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifié'), ('COMPLETED', 'Effectué'), ('CANCELLED', 'Annulé'), ('NO_SHOW', 'Absent')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='utilisateurs.mentorapplication')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entretien mentor',
                'verbose_name_plural': 'Entretiens mentor',
            },
        ),
        migrations.CreateModel(
            name='MentorSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Domaine principal, ex. Programmation', max_length=120)),
                ('specialization', models.CharField(blank=True, help_text='Spécialité, ex. JavaScript / Web', max_length=150)),
                ('declared_level', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé'), ('EXPERT', 'Expert')], default='INTERMEDIAIRE', max_length=20)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='utilisateurs.mentorapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compétence mentor',
                'verbose_name_plural': 'Compétences mentor',
                'ordering': ['domain', 'specialization'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_type', models.CharField(choices=[('DIPLOMA', 'Diplôme'), ('CERTIFICATE', 'Certificat'), ('ATTESTATION', 'Attestation'), ('PROFESSIONAL_LICENSE', 'Licence professionnelle'), ('EXPERIENCE', "Preuve d'expérience"), ('PORTFOLIO', 'Portfolio'), ('OTHER', 'Autre document')], default='DIPLOMA', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='mentors/qualifications/%Y/%m/')),
                ('reference', models.CharField(blank=True, help_text='Référence ou URL externe', max_length=150)),
                ('verification_status', models.CharField(choices=[('PENDING', 'En attente'), ('UNDER_REVIEW', 'En cours de vérification'), ('VERIFIED', 'Vérifié'), ('REJECTED', 'Rejeté'), ('NOT_VERIFIABLE', 'Non vérifiable')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='utilisateurs.mentorapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('IDENTITY', 'Identité'), ('DOCUMENT', 'Documents'), ('SKILL', 'Compétences'), ('EXPERIENCE', 'Expérience'), ('ASSESSMENT', 'Évaluation'), ('INTERVIEW', 'Entretien'), ('STATUS', 'Décision de statut')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('PASSED', 'Validé'), ('FAILED', 'Refusé'), ('INFO_REQUIRED', 'Informations requises')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('document_reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='utilisateurs.mentorapplication')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Décision de vérification',
                'verbose_name_plural': 'Décisions de vérification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('FALSE_IDENTITY', 'Fausse identité'), ('FALSE_QUALIFICATION', 'Fausse qualification'), ('INAPPROPRIATE_BEHAVIOUR', 'Comportement inapproprié'), ('FRAUD', 'Fraude'), ('HARASSMENT', 'Harcèlement'), ('SESSION_ISSUE', 'Problème pendant une session'), ('OTHER', 'Autre')], default='OTHER', max_length=30)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('UNDER_REVIEW', 'En cours d’investigation'), ('RESOLVED', 'Clôturé'), ('DISMISSED', 'Rejeté'), ('ACTION_TAKEN', 'Sanction appliquée')], default='OPEN', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement de mentor',
                'verbose_name_plural': 'Signalements de mentor',
                'ordering': ['-created_at'],
                'unique_together': {('mentor', 'reporter', 'reason')},
            },
        ),
    ]
