# Generated by Django 5.2.17 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_teacherapplication_review_note_teacherapplication_reviewed_at_teacherapplication_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherapplication',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='tutors/diplomas/'),
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='identity_card',
            field=models.FileField(blank=True, null=True, upload_to='tutors/id_cards/'),
        ),
    ]
