# Generated by Django 5.2.5 on 2026-09-24 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_tutorprofile_options_tutorprofile_education_and_more'),
        ('utilisateurs', '0004_teacherapplication_diploma_teacherapplication_identity_card'),
    ]

    operations = [
    ]
