# Generated by Django 5.2.17 on 2026-09-21 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_examquestion_examchoice_stateexam_examquestion_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('IMAGE', 'Image'), ('VIDEO', 'Vidéo'), ('OTHER', 'Autre fichier')], default='DOCUMENT', max_length=20)),
                ('file', models.FileField(upload_to='exam_archives/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('downloadable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.stateexam')),
            ],
        ),
    ]
