# Generated by Django 6.0.7 on 2026-09-24 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_archiveresource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptanswer',
            options={'verbose_name': 'Réponse de tentative', 'verbose_name_plural': 'Réponses de tentative'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Chapitre', 'verbose_name_plural': 'Chapitres'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Choix de réponse', 'verbose_name_plural': 'Choix de réponses'},
        ),
        migrations.AlterModelOptions(
            name='learnerquestion',
            options={'ordering': ['-created_at'], 'verbose_name': "Question d'apprenant", 'verbose_name_plural': "Questions d'apprenants"},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='learnerquestion',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_learner_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='allow_multiple_attempts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Catégorie utilisée pour le Quiz Game et le Quiz Training', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='courses.category'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.CharField(blank=True, help_text='Niveau de difficulté du Quiz Game', max_length=30),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0, help_text='0 = tentatives illimitées'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.PositiveIntegerField(default=70, help_text='Seuil de réussite en pourcentage'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='random_question_count',
            field=models.PositiveIntegerField(default=0, help_text='0 = toutes les questions, sinon nombre de questions tirées au hasard'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Temps réellement passé sur la tentative'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('SUBMITTED', 'Soumise'), ('EXPIRED', 'Expirée')], default='IN_PROGRESS', max_length=20),
        ),
    ]
