# Generated by Django 6.0.7 on 2026-09-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_attemptanswer_options_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='selected_question_ids',
            field=models.JSONField(blank=True, default=list, help_text='Questions présentées dans cette tentative, dans leur ordre.'),
        ),
    ]
