# Generated by Django 5.2.5 on 2026-09-24 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_quizattempt_selected_question_ids'),
        ('courses', '0009_enrollment_completed_at'),
    ]

    operations = [
    ]
