# Generated by Django 5.2.5 on 2026-09-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_archiveresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='all_quizzes_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='certification_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='minimum_progress',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='course',
            name='minimum_quiz_score',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=5),
        ),
        migrations.AddField(
            model_name='course',
            name='require_final_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='require_final_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='require_mentor_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_final_assessment',
            field=models.BooleanField(default=False),
        ),
    ]
