# Generated by Django 5.2.17 on 2026-09-21 07:55

import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_mentor_confirmed_booking_student_confirmed_and_more'),
        ('courses', '0002_initial'),
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=payments.models.generate_transaction_id, max_length=100, unique=True)),
                ('provider', models.CharField(default='fake', max_length=50)),
                ('payment_method', models.CharField(choices=[('TEST', 'Faux provider'), ('lumicash', 'Lumicash'), ('eco_cash', 'EcoCash'), ('bank_transfer', 'Virement bancaire'), ('bitcoin', 'Bitcoin (Lightning Network)')], default='TEST', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BIF', max_length=3)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('provider_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mentor_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('CREATED', 'Créée'), ('PENDING', 'En attente'), ('PROCESSING', 'En traitement'), ('FAILED', 'Échec'), ('PAID', 'Payée'), ('HELD', 'Bloquée jusqu’à libération'), ('READY_TO_RELEASE', 'Prête à être libérée'), ('RELEASED', 'Libérée'), ('COMPLETED', 'Terminée'), ('REFUND_PENDING', 'Remboursement en attente'), ('REFUNDED', 'Remboursée'), ('DISPUTED', 'Contestée'), ('PAYOUT_FAILED', 'Échec du versement')], default='CREATED', max_length=20)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='bookings.booking')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='courses.course')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=50)),
                ('chain_id', models.CharField(blank=True, max_length=50)),
                ('tx_hash', models.CharField(max_length=255, unique=True)),
                ('sender_address', models.CharField(blank=True, max_length=255)),
                ('receiver_address', models.CharField(blank=True, max_length=255)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_data', to='payments.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('provider_event_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.transaction')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
