# Generated by Django 5.2.5 on 2026-09-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='payment_request',
            field=models.TextField(blank=True),
        ),
    ]
