# Generated by Django 5.2.17 on 2026-09-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mentor_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='student_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de confirmation'), ('pending_payment', 'En attente de paiement'), ('accepted', 'Accepté par le professeur'), ('confirmed', 'Paiement confirmé'), ('in_progress', 'Session en cours'), ('rejected', 'Rejeté par le professeur'), ('completed', 'Session terminée'), ('disputed', 'Litige'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
