# Generated by Django 5.2.5 on 2026-09-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_course_title_certificate_final_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='study_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='study_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
